### ISSUE TITLE
라이센스 미이행

### ISSUE THREAD

**Issue by CwhiteKJ** [Krchip/PythonDiscordbot#1]
[사용하신 코드](https://github.com/Krchip/PythonDiscordbot/blob/master/main.py#L31) 의 코드 출처는 [미야](https://github.com/LRACT/Miya) 이며, GPLv3 라이센스를 적용 중입니다.

따라서, 라이센스를 이행하실 의무가 있으며 **사용하신 코드에 대한 출처를 기재** 해주시길바랍니다.

**Comment by Krchip** [comment]
방금전 라이선스 게제가 완료되었습니다.

불편을 드려 사과드립니다.

**Comment by CwhiteKJ** [comment]
불편하네요 대국민사과해주세요

**Comment by Krchip** [comment]
죄송합니다.

이용에 불편을 드려 사과드립니다.
